services:
  postgres:
    image: postgres:17
    container_name: postgres-warehouse
    restart: unless-stopped
    environment:
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker-volumes/postgres/opt:/var/lib/postgresql/opt
    networks:
      - platform-net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /opt/docker-volumes/redis/opt:/opt
    networks:
      - platform-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Sk@teordie2016?
    ports:
      - "5050:80"
    volumes:
      - /opt/docker-volumes/pgadmin:/var/lib/pgadmin
    networks:
      - platform-net
    depends_on:
      - postgres

networks:
  platform-net:
    external: true
